# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# Welcome to Colab!
"""

"""
Q1: Factorial helper.
"""

from __future__ import annotations


def factorial(n: int) -> int:
    """Return n! for non-negative integers."""
    if n < 0:
        raise ValueError("factorial is undefined for negative integers")
    result = 1
    for value in range(2, n + 1):
        result *= value
    return result


if __name__ == "__main__":
    for sample in range(6):
        print(f"{sample}! = {factorial(sample)}")



print("\n\n")

'''


I utilized the Cursor AI coding assistant to iteratively refine a Python function for calculating factorials, focusing on precision and validation.

Refinement Steps

1.  **Initial Request:**
    * **Prompt:** "Write a Python function to calculate the factorial of a number."
    * **Result:** Generated a basic iterative function but lacked explicit input validation.

2.  **Handling Zero ($0! = 1$):**
    * **Added Instruction:** "Make sure the function clearly handles zero and states $0! = 1$ in the docstring."
    * **Result:** The assistant retained the loop logic (which inherently handles zero correctly) and updated the function's docstring to explicitly mention the handling of $0! = 1$.

3.  **Input Validation (Rejecting Negatives):**
    * **Added Instruction:** "Raise a helpful exception whenever the input is negative."
    * **Result:** The assistant inserted the necessary validation logic: `if n < 0: raise ValueError(...)`.

Final Outcome

The complete process and the final code were recorded in `Q4_prompt.md`. Running the test script, `Q4.py`, successfully prints factorials for $0$ through $5$ and correctly raises a `ValueError` for negative inputs, satisfying all specified requirements.

'''

#2. -----------------------------
# Helper function to process marks
# -----------------------------
def analyze_marks(student_marks):
    """Compute mean and list students above mean."""
    marks = list(student_marks.values())
    mean_val = sum(marks) / len(marks)

    above_mean = [name for name, mark in student_marks.items() if mark > mean_val]

    return mean_val, above_mean


# -----------------------------
# Zero-Shot Example
# -----------------------------
print("=== ZERO SHOT PROMPT ===")

zero_shot_input = {
    "Aisha": 76,
    "Ben": 59,
    "Carlos": 91,
    "Dina": 84,
    "Evan": 67
}

mean_zero, above_zero = analyze_marks(zero_shot_input)

print("Input:", zero_shot_input)
print("Mean:", mean_zero)
print("Students above mean:", above_zero)


# -----------------------------
# One-Shot Example
# -----------------------------
print("\n=== ONE SHOT PROMPT ===")

# Example given to the AI
one_shot_example = {
    "John": 80,
    "Lila": 60,
    "Hari": 90
}
mean_ex, above_ex = analyze_marks(one_shot_example)

# New task
one_shot_input = zero_shot_input  # using same dataset for demonstration
mean_one, above_one = analyze_marks(one_shot_input)

print("Example Input:", one_shot_example)
print("Example Mean:", mean_ex)
print("Example Above Mean:", above_ex)

print("\nSolve this new case:")
print("Input:", one_shot_input)
print("Mean:", mean_one)
print("Students above mean:", above_one)


# -----------------------------
# Few-Shot Example
# -----------------------------
print("\n=== FEW SHOT PROMPT ===")

# Example 1
example1 = {
    "John": 80,
    "Lila": 60,
    "Hari": 90
}
mean1, above1 = analyze_marks(example1)

# Example 2
example2 = {
    "Mira": 50,
    "Noah": 72,
    "Omar": 88,
    "Pia": 92
}
mean2, above2 = analyze_marks(example2)

# New task
few_shot_input = zero_shot_input
mean_few, above_few = analyze_marks(few_shot_input)

print("Example 1 Input:", example1)
print("Example 1 Mean:", mean1)
print("Example 1 Above Mean:", above1)

print("\nExample 2 Input:", example2)
print("Example 2 Mean:", mean2)
print("Example 2 Above Mean:", above2)

print("\nSolve this new case:")
print("Input:", few_shot_input)
print("Mean:", mean_few)
print("Students above mean:", above_few)

